name: sirio_portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # intl: ^0.17.0
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  animate_do: ^3.0.2
  fluttertoast: ^8.1.2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon3.png"
  
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
